### ISSUE TITLE
Initial provision does not boot mongod server, but second provision attempt does - does anyone know why?

### ISSUE THREAD

**Issue by niftylettuce** [UnderGreen/ansible-role-mongodb#225]
Ubuntu 18.04 with defaults:

```sh
RUNNING HANDLER [mongodb restart] **********************************************
fatal: [my.secret.hostname]: FAILED! => {"changed": false, "msg": "Could not find the requested service mongod: host"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
my.secret.hostname : ok=57   changed=42   unreachable=0    failed=1    skipped=10   rescued=0    ignored=0
```

Then when I try it again, it works fine and `failed=0`.

**Comment by niftylettuce** [comment]
Here's some more verbose output, a slightly different warning message.  Curious if @UnderGreen has seen this?

```sh
RUNNING HANDLER [wait when mongodb is started] *********************************
failed: [XX] (item=127.0.0.1) => {"ansible_loop_var": "item", "changed": false, "elapsed": 120, "item": "127.0.0.1", "msg": "Timeout when waiting for 127.0.0.1:27017"}
failed: [XX] (item=1.2.3.4) => {"ansible_loop_var": "item", "changed": false, "elapsed": 120, "item": "1.2.3.4", "msg": "Timeout when waiting for 1.2.3.4:27017"}

RUNNING HANDLER [mongodb restart] **********************************************
```

Second boot works fine.  1.2.3.4 is an actual IP, I just renamed it for privacy.

**Comment by niftylettuce** [comment]
My setup can be found here: https://github.com/forwardemail/forwardemail.net/blob/master/ansible/playbooks/mongo.yml

**Comment by niftylettuce** [comment]
It seems like this is missing somewhere:

```sh
sudo systemctl enable mongod
sudo systemctl start mongod
```

**Comment by MemberIT** [comment]
@niftylettuce 
Hi, you can try to use the fork of role
https://github.com/sportsru/ansible-role-mongodb
and maybe you should set `mongodb_manage_systemd_unit: false` by starting the installation again.

**Comment by niftylettuce** [comment]
@MemberIT is this issue solved too?

https://github.com/UnderGreen/ansible-role-mongodb/issues/103

**Comment by MemberIT** [comment]
> @MemberIT is this issue solved too?
> 
> #103

No

**Comment by niftylettuce** [comment]
@MemberIT I just tried your fork.  It does not work.

```sh
RUNNING HANDLER [wait when mongodb is started] *********************************
ok: [HIDDEN] => (item=127.0.0.1)
```

Stuck on this.

**Comment by MemberIT** [comment]
> @MemberIT I just tried your fork. It does not work.
> 
> ```shell
> RUNNING HANDLER [wait when mongodb is started] *********************************
> ok: [HIDDEN] => (item=127.0.0.1)
> ```
> 
> Stuck on this.

I think you need to use `pymongo` from pip, because `pymongo` from deb not support mongodb 4.2.
https://pypi.org/project/pymongo/3.6.1/
https://github.com/forwardemail/forwardemail.net/blob/master/ansible/playbooks/mongo.yml#L9

**Comment by niftylettuce** [comment]
That seemed to fix it!!!!  THANK YOU!

If you have PayPal or BTC, please email me niftylettuce@gmail.com - would love to comp you for your help.

**Comment by MemberIT** [comment]
> > @MemberIT is this issue solved too?
> > #103
> 
> No

@niftylettuce Although no, I was mistaken, resolved here
https://github.com/UnderGreen/ansible-role-mongodb/commit/f8142e6d5a7255ecb7bf560a3319cf3f574455a6

**Comment by niftylettuce** [comment]
@MemberIT I still see that even your fork has this issue on first boot/provision:

```sh
RUNNING HANDLER [wait when mongodb is started] *********************************
```

Re-running provision fixes it.  Do you know what's wrong??
